### ISSUE TITLE
Create A Logo For Nephos

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/Nephos#79]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Nephos is a very crucial project and hence to increase the aesthetics of the Project it would be great to have an official logo for the client which we can post in the github repository.

**Describe alternatives you've considered**
..

**Additional context**
Contributors are also requested to add the logo by themselves and update the README.md accordingly.

**Comment by Freyam** [comment]
i made 2 logos for you on GCI....but they r telling me to 
 --Hi! You're also supposed to open a pull request adding the logo you made to the GitHub project repository :) https://github.com/thealphadollar/Nephos--
...now how do i open a pull request? 
can someone guide me!!

**Comment by Freyam** [comment]
![ccex project nephos logo1](https://user-images.githubusercontent.com/35898769/47608437-d1f32300-da3e-11e8-9af6-6afd826da1ba.png)
![ccex project nephos logo2](https://user-images.githubusercontent.com/35898769/47608438-d1f32300-da3e-11e8-9abe-8dfc5399cf94.png)
