### ISSUE TITLE
Create Debian Installation Script

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/Nephos#84]
**Is your feature request related to a problem? Please describe.**
Currently, we only have an installation script for CentOS, which is acceptable since the platform on which Nephos will be deployed is a CentOS system. However, it is desirable that, for the convinience of developers (and testers), we have an install script for Ubuntu/Debian.

**Describe the solution you'd like**
Using the install script written for CentOS; a new script can be created with instructions to install in a Debian based distro. A slightly better approach would be to find the platform automatically and then install the appropriate packages. The latter one is preferred since having two files for installation is tedious and few tasks are platform independent.

**Describe alternatives you've considered**
None.

**Additional context**
[This](https://www.shellscript.sh/) is a good tutorial to start with if you are new to shell scripting.

**Comment by MatejMecka** [comment]
#102 implements this

**Comment by thealphadollar** [comment]
fixed via #102
