### ISSUE TITLE
Update Pipfile Dependencies' Version

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/Nephos#90]
**Describe the bug**
Github reports of a vulnerability in the requests library version we are using. It can be easily updated using the following steps:

- Install pipenv
- Create pipenv shell for the project
- run `pipenv update`

**To Reproduce**
Nothing

**Expected behavior**
No vulnerability.

**Screenshots**
![screenshot from 2018-10-30 22-28-34](https://user-images.githubusercontent.com/32812320/47736183-1c211200-dc94-11e8-8045-09385c3dc018.png)

**Desktop (please complete the following information):**
 - requests version 2.18.0

**Additional context**
--

**Comment by MatejMecka** [comment]
#95 should update dependencies

**Comment by thealphadollar** [comment]
Closed via #95
